// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUnmqf0ajaZk9UIDEBo6OM1EQ9B7-S8dM',
    appId: '1:1000831129400:web:21ccc2b54754ee39e053cd',
    messagingSenderId: '1000831129400',
    projectId: 'mad-project-petcare',
    authDomain: 'mad-project-petcare.firebaseapp.com',
    storageBucket: 'mad-project-petcare.firebasestorage.app',
    measurementId: 'G-19HZ9R0WPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTTE084wRlb8uLwsjML_VCy2972Kt3i38',
    appId: '1:1000831129400:android:1312e7ef13254fe9e053cd',
    messagingSenderId: '1000831129400',
    projectId: 'mad-project-petcare',
    storageBucket: 'mad-project-petcare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfJZJ8qXrsbwneaSqnR-SWVMYoA7yE7hM',
    appId: '1:1000831129400:ios:a80f17ed8aac4956e053cd',
    messagingSenderId: '1000831129400',
    projectId: 'mad-project-petcare',
    storageBucket: 'mad-project-petcare.firebasestorage.app',
    iosBundleId: 'com.example.petcareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfJZJ8qXrsbwneaSqnR-SWVMYoA7yE7hM',
    appId: '1:1000831129400:ios:a80f17ed8aac4956e053cd',
    messagingSenderId: '1000831129400',
    projectId: 'mad-project-petcare',
    storageBucket: 'mad-project-petcare.firebasestorage.app',
    iosBundleId: 'com.example.petcareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUnmqf0ajaZk9UIDEBo6OM1EQ9B7-S8dM',
    appId: '1:1000831129400:web:ffbbec4858cc6046e053cd',
    messagingSenderId: '1000831129400',
    projectId: 'mad-project-petcare',
    authDomain: 'mad-project-petcare.firebaseapp.com',
    storageBucket: 'mad-project-petcare.firebasestorage.app',
    measurementId: 'G-V5QP0SD2F0',
  );
}
